# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\tmyservice\"\x1e\n\x0b\x44\x61taRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x0c\x44\x61taResponse\x12\r\n\x05reply\x18\x01 \x01(\t2G\n\tMyService\x12:\n\x07GetData\x12\x16.myservice.DataRequest\x1a\x17.myservice.DataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATAREQUEST']._serialized_start=28
  _globals['_DATAREQUEST']._serialized_end=58
  _globals['_DATARESPONSE']._serialized_start=60
  _globals['_DATARESPONSE']._serialized_end=89
  _globals['_MYSERVICE']._serialized_start=91
  _globals['_MYSERVICE']._serialized_end=162
# @@protoc_insertion_point(module_scope)
